name: secure_literals
description: "Encrypts sensitive data before storing in flutter projects"
version: 0.0.6
homepage: https://github.com/Jigarvarma2k20/secure-literals
repository: https://github.com/Jigarvarma2k20/secure-literals

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  code_builder: ^4.11.1
  dart_style: ^3.1.5
  yaml: ^3.1.3
  pointycastle: ^4.0.0
